services:
  mongo:
    image: mongo:${MONGO_VERSION}
    container_name: mongo
    networks:
      - net_A
    volumes:
      - mongo_data:/data/db
    ports:
      - ${MONGO_PORT}:27017
  server:
    build: ./app
    container_name: server
    networks:
      - net_A
    depends_on:
      - mongo
    ports:
      - 3003:3000

volumes:
  mongo_data:
    name: mongo_data

networks:
  net_A:
    name: net_A
